# --- Modern Kitty & Clipboard ---
set -g default-terminal "xterm-kitty"
set -ga terminal-overrides ",xterm-kitty:Tc"
set -g mouse on
set -g allow-passthrough on
set -s set-clipboard on
unbind -n MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane
# --- Disable Status line ---
set -g status off

# --- Prefix ---
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# --- pane highligting ---
set -g pane-border-style fg=colour236
set -g pane-active-border-style fg=colour120
set -g pane-border-indicators both

# --- Navigation & Resizing (Vim-Style) ---
bind -n M-1 select-pane -t:.0
bind -n M-2 select-pane -t:.1
bind -n M-3 select-pane -t:.2
bind -n M-4 select-pane -t:.3

# --- Copy Mode ---
set-window-option -g mode-keys vi
bind Escape copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# --- Hot Reload ---
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

