[owncloud_franz]
type = webdav
url = https://keilholz.biz/cloud/remote.php/dav/files/fkeilholz/
vendor = nextcloud
user = fkeilholz
pass = 3EYgo-FszQpNdJoY9Efi4hG5UoeG9GY7TYPU6sa4_hB9oXeOzHCngAVcCTXfysRB11XWjh1O6abgVdRGHMPgt8BPTXcxvppY2sF5jRPWLkQ

